# Permalinks
permalink:      /:year-:month-:day/:title

# Setup
title:          Yejikim
baseurl:        ""
url:            "https://yejikim93.github.io"

# Assets
sass:
  sass_dir:     _sass
  style:        :compressed

# Build settings
markdown:       kramdown

# About
author:
  name:         Yeji Kim
  url:          https://yejikim93.github.io/
  email:        yz6242@gmail.com
  github:       yejikim93
  twitter:      playpingpong

# Custom vars
version:        3.4.1
github:
  repo:         https://github.com/iamleejihye/iamleejihye.github.io
